### ISSUE TITLE
Cannot find name WebAssembly

### ISSUE THREAD

**Issue by jtenner** [marcj/typedoc-plugin-lerna-packages#20]
```
Error: .../as-pect/packages/core/src/util/IAspectExports.ts(66)
 Cannot find namespace 'WebAssembly'.
Error: .../as-pect/packages/core/src/util/wasmTools.ts(56)
 Cannot find name 'WebAssembly'.
Error: .../as-pect/packages/core/src/util/wasmTools.ts(57)
 Cannot find name 'WebAssembly'.
```

Mostly unsure what to do about this since that definition is in `lib.dom.d.ts` and it worked in version `0.2.2`.

Hoping to find a solution

**Comment by marcj** [comment]
Mh, does this come from newest Typedoc or this plugins? Please uninstall typedoc-plugin-lerna-packages and execute `typedoc` to see that we're the root cause of this issue. If typedoc builds correctly then we're probably the issue 🤷‍♂️

**Comment by ivan-nemtinov** [comment]
@jtenner To make this plugin work, you should set "mode": "modules" in typedoc.json

**Comment by jtenner** [comment]
@ivan-nemtinov thanks for the help. If I ever need to use this again, I will keep that in mind.

In the meantime, I switched to gitbook which now houses all of my documentation for my testing software. I'm just glad I could help surface this weird problem.
